### ISSUE TITLE
[security]: protect againt SQL injection

### ISSUE THREAD

**Issue by tyrossel** [Bima42/ft_transcendence#74]
Edit: We are already protected SQL injection thanks to Prisma. However, the following points would be nice to implement.

---

We have to validate each user input at least on the server side, and best would be on the client side too. And both side, we can use the [JOI](https://joi.dev/) package to help use

## Client side:

* Simple input: Add `pattern` attribute to all input field
* Alternative: add listeners to input field, that validate the input and/or warn the client

## Server side:

* Use DTOs for all things received from clients
* Decorate them with decorators from the JOI package

**Comment by Bima42** [comment]
Done by Prisma
